apiVersion: builtin
kind: LabelTransformer
metadata:
  name: helm-metadata-labels
labels:
  helm.sh/chart: '{{ include "ingress-template-operator.chart" . }}'
  app.kubernetes.io/name: ingress-template-controller
  app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
  app.kubernetes.io/managed-by: Helm
fieldSpecs:
  - path: metadata/labels
    create: true